/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsBoolean,
} from "class-validator";
import { EnrollmentUpdateManyWithoutCoursesInput } from "./EnrollmentUpdateManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { LessonUpdateManyWithoutCoursesInput } from "./LessonUpdateManyWithoutCoursesInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class CourseUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EnrollmentUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => EnrollmentUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => EnrollmentUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  enrollments?: EnrollmentUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => LessonUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => LessonUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => LessonUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  lessons?: LessonUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  published?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { CourseUpdateInput as CourseUpdateInput };
